version: '3'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: qloapp_mysql_container
    restart: unless-stopped
    expose:
      - "3306"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 30s
        timeout: 10s
        retries: 5    
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
  webserver:
    build:
      context: ./qloapp
      dockerfile: Dockerfile
    depends_on:  
       database:
          condition: service_healthy
    container_name: qloapp_container
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - webdata:/var/www/html
    networks:
      - app-network
      
volumes:
  webdata:
  dbdata:
networks:
  app-network:

